apiVersion: v1
kind: Service
metadata:
  name: dogbox-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  loadBalancerIP: 34.28.148.99
  selector:
    app: dogbox
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
